spring:
  application:
    name: mq-demo

rocketmq:
  name-server: 10.1.175.180:9876;10.1.175.198:9876;10.1.175.199:9876
  consumer:
    group: ${spring.application.name}
# ???????topic???????
consumer:
  topic: iot-analog,dev-analog

